version: '3.7'
services:

  config:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${CONFIG_SERVICE_DEV_DEBUG_PORT}
    build: config
    ports:
      - $CONFIG_SERVICE_DEV_PORT:$CONFIG_SERVICE_DEV_PORT
      - $CONFIG_SERVICE_DEV_DEBUG_PORT:$CONFIG_SERVICE_DEV_DEBUG_PORT

  registry:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${REGISTRY_SERVICE_DEV_DEBUG_PORT}
    build: registry
    ports:
      - $REGISTRY_SERVICE_DEV_PORT:$REGISTRY_SERVICE_DEV_PORT
      - $REGISTRY_SERVICE_DEV_DEBUG_PORT:$REGISTRY_SERVICE_DEV_DEBUG_PORT

  account-gateway:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${ACCOUNT_GATEWAY_DEV_DEBUG_PORT}
    build: account-gateway
    ports:
      - $ACCOUNT_GATEWAY_DEV_PORT:$ACCOUNT_GATEWAY_DEV_PORT
      - $ACCOUNT_GATEWAY_DEV_DEBUG_PORT:$ACCOUNT_GATEWAY_DEV_DEBUG_PORT

  account-auth:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${ACCOUNT_AUTH_DEV_DEBUG_PORT}
    build: account-auth
    ports:
      - $ACCOUNT_AUTH_DEV_PORT:$ACCOUNT_AUTH_DEV_PORT
      - $ACCOUNT_AUTH_DEV_DEBUG_PORT:$ACCOUNT_AUTH_DEV_DEBUG_PORT

  account-auth-mysqld:
    build: mysqld
    ports:
      - $ACCOUNT_AUTH_MYSQLDB_EXTERNAL_DEV_PORT:$MYSQLDB_SERVICE_INTERNAL_DEV_PORT

  account-service:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${ACCOUNT_SERVICE_DEV_DEBUG_PORT}
    build: account-service
    ports:
      - $ACCOUNT_SERVICE_DEV_PORT:$ACCOUNT_SERVICE_DEV_PORT
      - $ACCOUNT_SERVICE_DEV_DEBUG_PORT:$ACCOUNT_SERVICE_DEV_DEBUG_PORT

  account-mysqld:
    build: mysqld
    ports:
      - $MYSQLDB_ACCOUNT_EXTERNAL_DEV_PORT:$MYSQLDB_SERVICE_INTERNAL_DEV_PORT

  trainer-service:
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}${TRAINER_SERVICE_DEV_DEBUG_PORT}
    build: trainer-service
    ports:
      - $TRAINER_SERVICE_DEV_PORT:$TRAINER_SERVICE_DEV_PORT
      - $TRAINER_SERVICE_DEV_DEBUG_PORT:$TRAINER_SERVICE_DEV_DEBUG_PORT

  rabbitmq:
    ports:
      - $RABBITMQ_SERVICE_INTERNAL_DEV_PORT:$RABBITMQ_SERVICE_INTERNAL_DEV_PORT
