security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://account-auth:${ACCOUNT_AUTH_DEV_PORT}/mservicet/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://account-auth:${ACCOUNT_AUTH_DEV_PORT}/mservicet/users/current

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://training-mysqld:${MYSQLDB_SERVICE_INTERNAL_DEV_PORT}/trainingDB?useUnicode=yes&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: qwerty
    hikari:
      connection-timeout: "20000"
      minimum-idle: "5"
      maximum-pool-size: "12"
      idle-timeout: "300000"
      max-lifetime: "1200000"
  jpa:
    properties.hibernate:
      id.new_generator_mappings: "false"
      format_sql: "true"
    show-sql: "true"
    hibernate:
      ddl-auto: update
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

server:
  servlet:
    context-path: /accounts
  port: ${ACCOUNT_SERVICE_DEV_PORT}